[profile.default]
src = "contracts"
test = "tests"
out = "out"
libs = ["lib"]
solc = "/Library/Frameworks/Python.framework/Versions/3.10/bin/solc"
auto_detect_solc = false
offline = true
optimizer = true
optimizer_runs = 200
